# Generated by Django 4.0 on 2021-12-13 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_alter_hotel_notaavaliacao_alter_hotel_qualidadewifi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='maximoPessoas',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número máximo de pessoas'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Preço'),
        ),
    ]
