# Generated by Django 4.0 on 2021-12-13 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_alter_hotel_estabelecimento_alter_hotel_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='estaLivre',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=4, verbose_name='Está livre'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='notaAvaliacao',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Nota de Avaliação'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='qualidadeWifi',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Qualidade do WIFI'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='tvCabo',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=5, verbose_name='Tem TV a Cabo'),
        ),
    ]
