# Generated by Django 4.0 on 2021-12-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0006_alter_hotel_estalivre_alter_hotel_notaavaliacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospedagemReservada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeHospedagemReservada', models.CharField(max_length=60, verbose_name='')),
                ('dataEntrada', models.CharField(max_length=10, verbose_name='Insira a data de entrada no formato ( DD/MM/AAAA ) ')),
                ('dataSaida', models.CharField(max_length=10, verbose_name='Insira da ta de saída no formato ( DD/MM/AAAA ) ')),
                ('valorFinal', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='')),
            ],
        ),
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Hospedagem',
        ),
    ]
