# Generated by Django 4.0 on 2021-12-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0007_hospedagemreservada_rename_hotel_hospedagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospedagemreservada',
            name='valorFinal',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor final'),
        ),
    ]
