# Generated by Django 4.0 on 2021-12-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0008_alter_hospedagemreservada_valorfinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospedagemreservada',
            name='dataSaida',
            field=models.CharField(max_length=10, verbose_name='Insira data de saída no formato ( DD/MM/AAAA ) '),
        ),
    ]
