# Generated by Django 4.0 on 2021-12-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0009_alter_hospedagemreservada_datasaida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospedagemreservada',
            name='dataEntrada',
            field=models.DateTimeField(verbose_name='Insira a data de entrada no formato ( DD/MM/AAAA ) '),
        ),
        migrations.AlterField(
            model_name='hospedagemreservada',
            name='dataSaida',
            field=models.DateTimeField(verbose_name='Insira data de saída no formato ( DD/MM/AAAA ) '),
        ),
    ]
