# Generated by Django 4.0 on 2021-12-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0010_alter_hospedagemreservada_dataentrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospedagemreservada',
            name='dataSaida',
        ),
        migrations.AddField(
            model_name='hospedagemreservada',
            name='numeroDias',
            field=models.SmallIntegerField(default=0, verbose_name='Insira quantos dias deseja ficar '),
            preserve_default=False,
        ),
    ]
