# Generated by Django 4.0 on 2021-12-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0011_remove_hospedagemreservada_datasaida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospedagemreservada',
            name='dataEntrada',
            field=models.CharField(max_length=10, verbose_name='Insira a data de entrada no formato ( DD/MM/AAAA ) '),
        ),
        migrations.AlterField(
            model_name='hospedagemreservada',
            name='numeroDias',
            field=models.SmallIntegerField(verbose_name='Insira quantos dias deseja ficar'),
        ),
    ]
