# Generated by Django 4.0 on 2021-12-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0013_alter_hospedagemreservada_valorfinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospedagemreservada',
            name='valorFinal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name=''),
            preserve_default=False,
        ),
    ]
